In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [ ]:
train_file = pd.read_csv("train.csv")
test_file = pd.read_csv('test.csv')

In [ ]:
train_file

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [ ]:
test_file

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [ ]:
train_file.drop(['PassengerId', 'Name'], axis=1, inplace=True)
test_file.drop(['PassengerId', 'Name'], axis=1, inplace=True)

In [ ]:
train_file

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8688,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

In [ ]:
train_file.isnull().sum()

HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Transported       0
dtype: int64

In [ ]:
test_file.isnull().sum()

HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
dtype: int64

In [ ]:
train_file.fillna({
    'HomePlanet': train_file['HomePlanet'].mode()[0],
    'CryoSleep': train_file['CryoSleep'].mode()[0],
    'Cabin': train_file['Cabin'].mode()[0],
    'Destination': train_file['Destination'].mode()[0],
    'VIP': train_file['VIP'].mode()[0],
    'Age': train_file['Age'].median(),
    'RoomService': train_file['RoomService'].median(),
    'FoodCourt': train_file['FoodCourt'].median(),
    'ShoppingMall': train_file['ShoppingMall'].median(),
    'Spa': train_file['Spa'].median(),
    'VRDeck': train_file['VRDeck'].median()
}, inplace=True)

C:\Users\BABAR\AppData\Local\Temp\ipykernel_12744\4135827501.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_file.fillna({

In [ ]:
test_file.fillna({
    'HomePlanet': test_file['HomePlanet'].mode()[0],
    'CryoSleep': test_file['CryoSleep'].mode()[0],
    'Cabin': test_file['Cabin'].mode()[0],
    'Destination': test_file['Destination'].mode()[0],
    'VIP': test_file['VIP'].mode()[0],
    'Age': test_file['Age'].median(),
    'RoomService': test_file['RoomService'].median(),
    'FoodCourt': test_file['FoodCourt'].median(),
    'ShoppingMall': test_file['ShoppingMall'].median(),
    'Spa': test_file['Spa'].median(),
    'VRDeck': test_file['VRDeck'].median()
}, inplace=True)

In [ ]:
train_file.isnull().sum()

HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
dtype: int64

In [ ]:
test_file.isnull().sum()

HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [ ]:
train_file.dtypes

HomePlanet       object
CryoSleep          bool
Cabin            object
Destination      object
Age             float64
VIP                bool
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Transported        bool
dtype: object

In [ ]:
categorical_cols = ['HomePlanet', 'Destination']
train_data = pd.get_dummies(train_file, columns=categorical_cols, drop_first=True)

In [ ]:
categorical_cols = ['HomePlanet', 'Destination']
test_data = pd.get_dummies(test_file, columns=categorical_cols, drop_first=True)

In [ ]:
train_data.dtypes

CryoSleep                       bool
Cabin                         object
Age                          float64
VIP                             bool
RoomService                  float64
FoodCourt                    float64
ShoppingMall                 float64
Spa                          float64
VRDeck                       float64
Transported                     bool
HomePlanet_Europa               bool
HomePlanet_Mars                 bool
Destination_PSO J318.5-22       bool
Destination_TRAPPIST-1e         bool
dtype: object

In [ ]:
test_data.dtypes

CryoSleep                       bool
Cabin                         object
Age                          float64
VIP                             bool
RoomService                  float64
FoodCourt                    float64
ShoppingMall                 float64
Spa                          float64
VRDeck                       float64
HomePlanet_Europa               bool
HomePlanet_Mars                 bool
Destination_PSO J318.5-22       bool
Destination_TRAPPIST-1e         bool
dtype: object

In [ ]:
train_data

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,HomePlanet_Europa,HomePlanet_Mars,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,False,B/0/P,39.0,False,0.0,0.0,0.0,0.0,0.0,False,True,False,False,True
1,False,F/0/S,24.0,False,109.0,9.0,25.0,549.0,44.0,True,False,False,False,True
2,False,A/0/S,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,True,False,False,True
3,False,A/0/S,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,True,False,False,True
4,False,F/1/S,16.0,False,303.0,70.0,151.0,565.0,2.0,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,False,A/98/P,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False,True,False,False,False
8689,True,G/1499/S,18.0,False,0.0,0.0,0.0,0.0,0.0,False,False,False,True,False
8690,False,G/1500/S,26.0,False,0.0,0.0,1872.0,1.0,0.0,True,False,False,False,True
8691,False,E/608/S,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False,True,False,False,False
8692,False,E/608/S,44.0,False,126.0,4688.0,0.0,0.0,12.0,True,True,False,False,True

In [ ]:
train_data.drop(['Cabin'], axis=1, inplace=True)

In [ ]:
test_data.drop(['Cabin'], axis=1, inplace=True)

In [ ]:
test_data

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Europa,HomePlanet_Mars,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,1,27,0,0,0,0,0,0,0,0,0,1
1,0,19,0,0,9,0,2823,0,0,0,0,1
2,1,31,0,0,0,0,0,0,1,0,0,0
3,0,38,0,0,6652,0,181,585,1,0,0,1
4,0,20,0,10,0,635,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1,34,0,0,0,0,0,0,0,0,0,1
4273,0,42,0,0,847,17,10,144,0,0,0,1
4274,1,26,0,0,0,0,0,0,0,1,0,0
4275,0,26,0,0,2680,0,0,523,1,0,0,1
4276,1,43,0,0,0,0,0,0,0,0,1,0

In [ ]:
test_data

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Europa,HomePlanet_Mars,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,1,27,0,0,0,0,0,0,0,0,0,1
1,0,19,0,0,9,0,2823,0,0,0,0,1
2,1,31,0,0,0,0,0,0,1,0,0,0
3,0,38,0,0,6652,0,181,585,1,0,0,1
4,0,20,0,10,0,635,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1,34,0,0,0,0,0,0,0,0,0,1
4273,0,42,0,0,847,17,10,144,0,0,0,1
4274,1,26,0,0,0,0,0,0,0,1,0,0
4275,0,26,0,0,2680,0,0,523,1,0,0,1
4276,1,43,0,0,0,0,0,0,0,0,1,0

In [ ]:
train_data.dtypes

CryoSleep                       bool
Age                          float64
VIP                             bool
RoomService                  float64
FoodCourt                    float64
ShoppingMall                 float64
Spa                          float64
VRDeck                       float64
Transported                     bool
HomePlanet_Europa               bool
HomePlanet_Mars                 bool
Destination_PSO J318.5-22       bool
Destination_TRAPPIST-1e         bool
dtype: object

In [ ]:
for col in train_data.columns:
    if train_data[col].dtype == 'bool':
        train_data[col] = train_data[col].astype(int)
    elif train_data[col].dtype == 'float64':
        train_data[col] = train_data[col].astype(int)

In [ ]:
for col in test_data.columns:
    if test_data[col].dtype == 'bool':
        test_data[col] = test_data[col].astype(int)
    elif test_data[col].dtype == 'float64':
        test_data[col] = test_data[col].astype(int)

In [ ]:
x = train_data.drop(['Transported'], axis=1)
y = train_data['Transported'].astype(int)

In [ ]:
RFC = RandomForestClassifier(random_state=42)
RFC.fit(x, y)

RandomForestClassifier(random_state=42)

In [ ]:
predictions = RFC.predict(test_data)
dump = pd.read_csv('test.csv')
submission = pd.DataFrame({'PassengerId':dump['PassengerId'],'Transported':predictions})
submission.to_csv('Submission.csv',index = False )

In [ ]:
indexed = pd.read_csv('Submission.csv')
indexed= indexed.applymap(lambda x: True if x == 1 else (False if x == 0 else x))
indexed.to_csv('Final_Submission.csv',index=False)